const consoleElement = document.getElementById('console');
const commands = [
    'Transferring Your Whatsapp to 03141828330...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',


    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Hacking Your from Whatsapp...',
    'Getting Data from Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Hacking Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',
    'Loading Whatsapp...',

    'By 03141828330...'
];

let commandIndex = 0;
const typingSpeed = 2;
const lineDelay = 20;

function typeCommand(command, callback) {
    let index = 0;

    function typeChar() {
        if (index < command.length) {
            consoleElement.innerHTML += command[index];
            index++;
            setTimeout(typeChar, typingSpeed);
        } else {
            consoleElement.innerHTML += '<br>';
            if (callback) callback();
        }
    }

    typeChar();
}

function showNextCommand() {
    if (commandIndex < commands.length) {
        typeCommand(commands[commandIndex], () => {
            commandIndex++;
            setTimeout(showNextCommand, lineDelay);
        });
    } else {
        consoleElement.innerHTML += '<span class="blinking-cursor">|</span>';
    }
}

setTimeout(showNextCommand, lineDelay);
